### ISSUE TITLE
'Plugin has crashed.' if any related games were deleted without uninstalling before

### ISSUE THREAD

**Issue by EustaceCS** [Mixaill/galaxy-integration-wargaming#10]
Plugin log: https://pastebin.com/6jh2C9CB
Environment: Galaxy 2.0.4 , Win10

Steps:
1. Cloned the plugin to needed %appdata%/... folder
2. Ran Galaxy
3. Tried to Add New Integration > Wargaming

Actual result: got 'Plugin has crashed' _and_ 'Connect' button changed to 'Disconnect'
Expected result: it either crashes or connects successfully, not both.

Additional intel:
As per what I see in logs, it tries to look for games way before authorization attempt (which is a... questionable sequence).
One of their games was indeed installed at D:\Games\WG\t\ path mentioned in logs some time ago.
I, however, was unable to find any registry keys which could still point at that location.
I believe, this location has been fetched from
C:\ProgramData\Wargaming.net\GameCenter\apps\wot\[whichever_temporary_file_user_may_have_there]
Full removal of
C:\ProgramData\Wargaming.net
folder solved the issue completely.

**Comment by Mixaill** [comment]
Should be fixed in ff5430f6f69b433c5f59ec5dde2400ab5110e52b
