### ISSUE TITLE
Games which are not owned are appearing

### ISSUE THREAD

**Issue by EustaceCS** [Mixaill/galaxy-integration-wargaming#11]
![1](https://user-images.githubusercontent.com/29461793/62831466-4bec4580-bc28-11e9-90b2-5a37ad604a29.PNG)
Logs:
https://pastebin.com/d9ekvWA0
Result upon attempt to Install the game from Galaxy:
![2](https://user-images.githubusercontent.com/29461793/62831482-af767300-bc28-11e9-9b29-5813adbf2de8.PNG)

**Comment by Mixaill** [comment]
Fixed in 0.7.4
https://github.com/Mixaill/galaxy-integration-wargaming/releases

You should to disconnect wargaming and connect it again to make Pagan disappear.
