### ISSUE TITLE
Connection to eu.wargaming.net not working

### ISSUE THREAD

**Issue by adb76** [Mixaill/galaxy-integration-wargaming#12]
When I try to connect GOG 2.0 to eu.wargaming.net I get the following error in the logfile:

[https://pastebin.com/vSeDwEcD](https://pastebin.com/vSeDwEcD)

Double-checked the credentials via browser - there they I working. Please give me an hint if you need further informations.

Regards.

**Comment by Mixaill** [comment]
@adb76 Please try the latest version and reupload logs with it.

**Comment by adb76** [comment]
Ok, that is strange - did you change more than just to logging? It worked directly with the new version. Here is the log:

[https://pastebin.com/1dsC62Qn](https://pastebin.com/1dsC62Qn)

**Comment by Mixaill** [comment]
Yeah, I've also tried to fix one possible reason, when WG server requires more than one redirects to another link.

**Comment by adb76** [comment]
Yes indeed! It works now flawlessly. Thanks!
