### ISSUE TITLE
No action on install if no Wargaming client installed

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#13]
Hey,

currently if a user has no Wargaming client installed but connects the plugin and clicks 'Install' on one of the available games (World of Tanks EU in this example) then nothing happens.

> 2019-10-10 09:23:34,033 - urllib3.connectionpool - DEBUG - https://wgcps-eu.wargaming.net:443 "POST /platform/api/v1/fetchProductList HTTP/1.1" 200 254
> 2019-10-10 09:23:34,037 - urllib3.connectionpool - DEBUG - Resetting dropped connection: cdn-eu-platform.gcdn.co
> 2019-10-10 09:23:34,062 - urllib3.connectionpool - DEBUG - https://cdn-eu-platform.gcdn.co:443 "GET /product/files/Y2JgYMzdvF4ygWFLQVFqUWphaWZxZklqfFlmanl8eX5JfHESA0NqqV55erJuQJC_S6hziKe_n665MQ7BPAYEAErHF2fklycnFqdClTPYf4DIAQA HTTP/1.1" 200 376
> 2019-10-10 09:23:34,102 - urllib3.connectionpool - DEBUG - https://wguscs-wotru.wargaming.net:443 "GET /api/v16/content/showroom/?lang=EN&gameid=WGC.RU.PRODUCTION&format=json&country_code=&showcase_products=WOT.SB.PRODUCTION@https://wgus-wotru.wargaming.net HTTP/1.1" 200 7705
> 2019-10-10 09:23:34,103 - root - WARNING - WGCOwnedApplicationInstance/install_application: failed to install WOT.EU.PRODUCTION because WGC is not installed

I think this case could be more user friendly if they were given some indicator what to do (maybe open up the 'https://eu.wargaming.net/support/en/products/wgc/article/10301/#section_0' page  using 

```
import webbrowser
webbrowser.open()
```

Hope this helps.

**Comment by Mixaill** [comment]
Fixed in 8d389fc27530c4fe996f7d02e53e02b6dd9a83ee
