### ISSUE TITLE
Plugin does not recognize that a game was installed until restarting galaxy.

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#14]
Hey,

I've started up the plugin without a Wargaming client, installed Wargaming client and then proceeded to click Install in Galaxy on World of Tanks EU. This caused installation to proceed and after it finished the plugin did not detect that the game was installed.

![image](https://user-images.githubusercontent.com/48480506/66554910-11caf180-eb4e-11e9-9bb8-4089fa64bbd0.png)

The plugin correctly recognized that the game was installed after restarting galaxy client. 

[plugin-wargaming-91728e8a-33c3-4b6d-8382-4dd31043dec1.log](https://github.com/Mixaill/galaxy-integration-wargaming/files/3711507/plugin-wargaming-91728e8a-33c3-4b6d-8382-4dd31043dec1.log)

Hope this helps

**Comment by Kothra** [comment]
I have a similar issue, specifically with World of Warships NA. The Galaxy client never recognized that the game was installed, and clicking install would open WGC.

Restarting Galaxy had no effect.

I reinstalled World of Warships (initiated with Galaxy's Install button), but it still doesn't recognize that the game is installed, even after restarting Galaxy.

**Comment by fox117** [comment]
I have a similar issue for World Of Warship EU and World Of Tank EU. The Galaxy client never recognized that the game was installed, and clicking install would open WGC. Restarting Galaxy had no effect.

![Capture](https://user-images.githubusercontent.com/13384039/67620823-4526a500-f80b-11e9-8f1d-c0a7e795bad0.JPG)
![Capture2](https://user-images.githubusercontent.com/13384039/67620826-4a83ef80-f80b-11e9-9846-e3a052fed320.JPG)

**Comment by Mixaill** [comment]
@FriendsOfGalaxy fixed in 3a9f61eb37e1c998cd6cf203ade10be50a546eea

**Comment by Mixaill** [comment]
@Kothra @fox117 fixed in fc82f1f62dc6ad0abac48f77076e14f9e2f9a39a
