### ISSUE TITLE
Games for regions not available for play showing

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#15]
Hey,

I have an EU account on the Wargaming platform and i used it to log in into the Wargaming integration. Afterwards the integration proceeds to list all possible regions for the selected game (World of Tank RU for example). 

If i try to launch RU version of World of Tanks it won't work with my EU account as it won't pass the in-game logging screen. 

I think it would be more intuitive to only show (send to Galaxy as owned) the game version corresponding to the region the user selected when logging in to integration. Its a suggestion though.

**Comment by Mixaill** [comment]
Fixed in 99f3eae62107abdae0878f0f48019665d86bcdcb
