### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#16]
Helo,

as you know, we're planning on creating a fork/autoupdate system with selected plugins and Wargaming is welcomed as well!

The standard request for you to fill our autoupdate system requirements:
- is deployed on branch named "fog_release" or default branch if "fog_release" doesn't exists
- does NOT include build Python dependencies 
- has requirements.txt in repository root
    - dependencies are pinned (onlly using '==') - this is for easier security checks and building final package by us
- has valid manifest.json with all fields listed in API documentation
    - "version" - in Semantic Versioning but without extensions like "beta" - to be comparable
    - "script" - cannot link to upper directory file (parent directory of manifest.json is treated as code source and only this is copied to final package while building)

**Comment by Mixaill** [comment]
@FriendsOfGalaxy please check

**Comment by FriendsOfGalaxy** [comment]
Thanks, structure is OK, build is passing.
Please take a look on our comments here: https://github.com/FriendsOfGalaxy/galaxy-integration-wargaming/pull/1#pullrequestreview-311145070
