### ISSUE TITLE
Cannot login (EU)

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#20]
I cannot authenticate in 0.8.0 for EU regime. "Login failed" is all I got, while those credentials are OK on wargaming.net. Tried with 2 accounts.

[plugin-wargaming-91728e8a-33c3-4b6d-8382-4dd31043dec1.log.txt](https://github.com/Mixaill/galaxy-integration-wargaming/files/3869014/plugin-wargaming-91728e8a-33c3-4b6d-8382-4dd31043dec1.log.txt)

**Comment by ciaron88** [comment]
same for me

**Comment by Mixaill** [comment]
Should be fixed in v0.8.1 

https://github.com/Mixaill/galaxy-integration-wargaming/releases/tag/v0.8.1
