### ISSUE TITLE
User WoT presence activated when plugin is running on user's machine.

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#22]
My friend is shown as online with description `Playing - World of Tanks EU` even when it is not playing. But he is connected to Galaxy via this plugin as well. When closing Galaxy - presence turns to offline.

Expected: connecting to plugin does not influence actual presence. Or at least it is shown just as "Online".

Extended logs in plugin gave:

```
logging.debug(self.client_roster[jid].resources)
```
```
2020-03-02 16:40:23,926 - root - DEBUG - {'wot': {'status': '', 'show': '', 'priority': 0}}
```

**Comment by Mixaill** [comment]
Should be fixed in https://github.com/Mixaill/galaxy-integration-wargaming/commit/8df01d39f8e2246584c49b633f0b85ff50a7d710

**Comment by FriendsOfGalaxy** [comment]
Works nice!
