### ISSUE TITLE
Plugin crashes on startup if WGC is not installed

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#24]
**Win/Mac | no WGC installed**

**Repro:**
Try to connect to the plugin while Wargaming.net Game Center is not installed.

**What happened:**
Plugin crashes.

**Expected:**
No crashes on plugin start.

**Comment by Mixaill** [comment]
Fixed in 5eaf86b367c1e2a187ccd26d4a2368f068f7766c

**Comment by Mixaill** [comment]
Fix released in v0.9.2 
https://github.com/Mixaill/galaxy-integration-wargaming/releases/tag/v0.9.2
