### ISSUE TITLE
Plugin becomes unresponsive and then crashes on login if wrong password is entered

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [Mixaill/galaxy-integration-wargaming#25]
**Win/Mac | in the login window**

**Repro:**
Bring up the login window and enter a wrong password (may need to repeat a couple of times).

**What happened:**
Login window disappears, plugin goes unresponsive for a split second and then crashes. Retrying brings up the login window again.

**Expected:**
Login window stays open, information about wrong credentials is displayed.

**Comment by Mixaill** [comment]
fixed in cfbfcbefe3520085ce68941003286d8fdbcb2fe4

**Comment by Mixaill** [comment]
Fix released in v0.9.2 
https://github.com/Mixaill/galaxy-integration-wargaming/releases/tag/v0.9.2
