### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by UncleGoogle** [Mixaill/galaxy-integration-wargaming#3]
Using freshly created account w/o 2FA.

```'Failed to request token by email and password'```

Successfully login into client and webpage

**Comment by Mixaill** [comment]
Can you please specify on which Wargaming.net realm you trying to connect?

**Comment by Mixaill** [comment]
Reproduced. Sometimes it connects only since second try O_o

**Comment by UncleGoogle** [comment]
Works perfectly, thanks!
