### ISSUE TITLE
Game time not imported

### ISSUE THREAD

**Issue by fgblomqvist** [Mixaill/galaxy-integration-wargaming#30]
The plugin says it imports game time, but it doesn't work for me.  It's just blank. Can't find any API calls for it in the code either 🤔

**Comment by Mixaill** [comment]
Unfortunately, it is impossible for Wargaming import game time (there is no such information in WGC or Public API for games) =(.

This integration only counts game time when game was started via GOG.

**Comment by fgblomqvist** [comment]
Hmm alright

**Comment by fgblomqvist** [comment]
Will the game time sync permanently to GOG with this plugin? I tried removing the plugin and the time it had tracked so far (5 minutes of testing) did not come back when I re-added it.
