### ISSUE TITLE
plugin connect to same "realm", but i can't see any games

### ISSUE THREAD

**Issue by easyentry** [Mixaill/galaxy-integration-wargaming#31]
Hello,
could you please help me with one issue I have?
I added the plugin via GOG search, I put the same account I use in Wargaming Game Center (with the same realm "EU") to the login there.
Still, I can't see any installed Wargaming games in GOG. (screenshot included)
![warg](https://user-images.githubusercontent.com/56564697/94987214-c7176600-0564-11eb-94b8-fd081741fd39.jpg)
I am available for the testing if it is needed.
Thanks for reply.

**Comment by Mixaill** [comment]
Please attach `C:\ProgramData\GOG.com\Galaxy\logs\plugin-wargaming-....log`

**Comment by easyentry** [comment]
Here they are:
[logs_wg_z.zip](https://github.com/Mixaill/galaxy-integration-wargaming/files/5324469/logs_wg_z.zip)

**Comment by Mixaill** [comment]
For some reason you was not updated to the v0.9.3

Try to 
- disconnect Wargaming
- click on `sync integrations`
- connect to the Wargaming again

Or just replace content of `%localappdata%\GOG.com\Galaxy\plugins\installed\wargaming-...\` with the content of the following archive:

https://github.com/Mixaill/galaxy-integration-wargaming/releases/download/v0.9.3/galaxy-integration-wargaming_v0.9.3.zip

**Comment by easyentry** [comment]
yep, it is working now.
you can close this topic.
many thanks.
