### ISSUE TITLE
wargaming games not detected

### ISSUE THREAD

**Issue by steffenw94** [Mixaill/galaxy-integration-wargaming#33]
Hi,

i installed newest version of the integration

i installed game world of tanks and world of warships in Wargaming Game Center launcher

the games are not detected in GOG Galaxy as installed. In Case of World of Warships its not possible to link manual start file of the game because its also linked to Steam. But both games does not appear in GOG Launcher

**Comment by Mixaill** [comment]
Fixed in v0.9.4

https://github.com/Mixaill/galaxy-integration-wargaming/releases/latest
